--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type Integer is
   new Standard.Integer;

  --  integer'Object_Size ~= 32 bits

  Integer_Default_Value : constant Integer :=
   0;

end PolyORB_HI_Generated.Types;
