--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Deployment is

  pragma Preelaborate;

  --  For each node in the distributed application add an enumerator

  type Node_Type is
   (main_K);

  --  Representation clause to have consistent positions for enumerators

  for Node_Type use
   (main_K =>
     1);

  --  Size of Node_Type fixed to 8 bits

  for Node_Type'Size use 8;

  Max_Node_Image_Size : constant Standard.Integer :=
   6;

  --  Maximal Node_Image size for this node

  --  Node Image

  subtype UT_Deployment_Main_Node_Type_Range is
   Node_Type range Node_Type'First .. Node_Type'Last;

  subtype UT_Deployment_Main_1_Max_Node_Image_Size is
   Integer range 1 .. Max_Node_Image_Size;

  subtype UT_Deployment_Main_Node_Image_Component is
   Standard.String
     (UT_Deployment_Main_1_Max_Node_Image_Size);

  type UT_Deployment_Main_Node_Image_Array is
   array (UT_Deployment_Main_Node_Type_Range)
     of UT_Deployment_Main_Node_Image_Component;

  Node_Image : constant UT_Deployment_Main_Node_Image_Array :=
   UT_Deployment_Main_Node_Image_Array'
     (main_K =>
       "main_K");

  My_Node : constant Node_Type :=
   main_K;

  --  For each thread in the distributed application nodes, add an enumerator

  type Entity_Type is
   (main_inductive_loop_in_thread_K,
    main_plates_data_thread_K,
    main_car_passed_entry_thread_K,
    main_car_parked_thread_K,
    main_car_moved_thread_K,
    main_inductive_loop_out_thread_K,
    main_calculate_price_K,
    main_open_gate_out_thread_K,
    main_car_passed_exit_thread_K);

  --  Representation clause to have consistent positions for enumerators

  for Entity_Type use
   (main_inductive_loop_in_thread_K =>
     1,
    main_plates_data_thread_K =>
     2,
    main_car_passed_entry_thread_K =>
     3,
    main_car_parked_thread_K =>
     4,
    main_car_moved_thread_K =>
     5,
    main_inductive_loop_out_thread_K =>
     6,
    main_calculate_price_K =>
     7,
    main_open_gate_out_thread_K =>
     8,
    main_car_passed_exit_thread_K =>
     9);

  --  Size of Entity_Type fixed to 8 bits

  for Entity_Type'Size use 8;

  --  Entity Table

  subtype UT_Deployment_Main_Entity_Type_Range is
   Entity_Type range Entity_Type'First .. Entity_Type'Last;

  type UT_Deployment_Main_Entity_Table_Array is
   array (UT_Deployment_Main_Entity_Type_Range)
     of Node_Type;

  Entity_Table : constant UT_Deployment_Main_Entity_Table_Array :=
   UT_Deployment_Main_Entity_Table_Array'
     (main_inductive_loop_in_thread_K =>
       main_K,
      main_plates_data_thread_K =>
       main_K,
      main_car_passed_entry_thread_K =>
       main_K,
      main_car_parked_thread_K =>
       main_K,
      main_car_moved_thread_K =>
       main_K,
      main_inductive_loop_out_thread_K =>
       main_K,
      main_calculate_price_K =>
       main_K,
      main_open_gate_out_thread_K =>
       main_K,
      main_car_passed_exit_thread_K =>
       main_K);

  Max_Entity_Image_Size : constant Standard.Integer :=
   32;

  --  Maximal Entity_Image size for this node

  --  Entity Image

  subtype UT_Deployment_Main_1_Max_Entity_Image_Size is
   Integer range 1 .. Max_Entity_Image_Size;

  subtype UT_Deployment_Main_Entity_Image_Component is
   Standard.String
     (UT_Deployment_Main_1_Max_Entity_Image_Size);

  type UT_Deployment_Main_Entity_Image_Array is
   array (UT_Deployment_Main_Entity_Type_Range)
     of UT_Deployment_Main_Entity_Image_Component;

  Entity_Image : constant UT_Deployment_Main_Entity_Image_Array :=
   UT_Deployment_Main_Entity_Image_Array'
     (main_inductive_loop_in_thread_K =>
       "main_inductive_loop_in_thread_K ",
      main_plates_data_thread_K =>
       "main_plates_data_thread_K       ",
      main_car_passed_entry_thread_K =>
       "main_car_passed_entry_thread_K  ",
      main_car_parked_thread_K =>
       "main_car_parked_thread_K        ",
      main_car_moved_thread_K =>
       "main_car_moved_thread_K         ",
      main_inductive_loop_out_thread_K =>
       "main_inductive_loop_out_thread_K",
      main_calculate_price_K =>
       "main_calculate_price_K          ",
      main_open_gate_out_thread_K =>
       "main_open_gate_out_thread_K     ",
      main_car_passed_exit_thread_K =>
       "main_car_passed_exit_thread_K   ");

  --  For each thread port in the distributed application nodes, add an 
  --  enumerator

  type Port_Type is
   (main_inductive_loop_in_thread_car_on_loop_K,
    main_inductive_loop_in_thread_recognize_plates_in_K,
    main_plates_data_thread_plates_data_in_K,
    main_plates_data_thread_plates_data_in_event_K,
    main_plates_data_thread_open_gate_in_K,
    main_car_passed_entry_thread_car_on_loop_K,
    main_car_passed_entry_thread_close_gate_K,
    main_car_parked_thread_slots_number_K,
    main_car_parked_thread_car_parked_K,
    main_car_moved_thread_slots_number_K,
    main_car_moved_thread_car_moved_K,
    main_inductive_loop_out_thread_car_on_loop_K,
    main_inductive_loop_out_thread_recognize_plates_out_K,
    main_calculate_price_plate_number_event_K,
    main_calculate_price_plate_number_K,
    main_calculate_price_calculated_price_K,
    main_open_gate_out_thread_parking_paid_K,
    main_open_gate_out_thread_open_gate_out_K,
    main_car_passed_exit_thread_car_on_loop_K,
    main_car_passed_exit_thread_close_gate_K);

  --  Representation clause to have consistent positions for enumerators

  for Port_Type use
   (main_inductive_loop_in_thread_car_on_loop_K =>
     1,
    main_inductive_loop_in_thread_recognize_plates_in_K =>
     2,
    main_plates_data_thread_plates_data_in_K =>
     3,
    main_plates_data_thread_plates_data_in_event_K =>
     4,
    main_plates_data_thread_open_gate_in_K =>
     5,
    main_car_passed_entry_thread_car_on_loop_K =>
     6,
    main_car_passed_entry_thread_close_gate_K =>
     7,
    main_car_parked_thread_slots_number_K =>
     8,
    main_car_parked_thread_car_parked_K =>
     9,
    main_car_moved_thread_slots_number_K =>
     10,
    main_car_moved_thread_car_moved_K =>
     11,
    main_inductive_loop_out_thread_car_on_loop_K =>
     12,
    main_inductive_loop_out_thread_recognize_plates_out_K =>
     13,
    main_calculate_price_plate_number_event_K =>
     14,
    main_calculate_price_plate_number_K =>
     15,
    main_calculate_price_calculated_price_K =>
     16,
    main_open_gate_out_thread_parking_paid_K =>
     17,
    main_open_gate_out_thread_open_gate_out_K =>
     18,
    main_car_passed_exit_thread_car_on_loop_K =>
     19,
    main_car_passed_exit_thread_close_gate_K =>
     20);

  --  Size of Port_Type fixed to 16 bits

  for Port_Type'Size use 16;

  --  Port Table

  subtype UT_Deployment_Main_Port_Type_Range is
   Port_Type range Port_Type'First .. Port_Type'Last;

  type UT_Deployment_Main_Port_Table_Array is
   array (UT_Deployment_Main_Port_Type_Range)
     of Entity_Type;

  Port_Table : constant UT_Deployment_Main_Port_Table_Array :=
   UT_Deployment_Main_Port_Table_Array'
     (main_inductive_loop_in_thread_car_on_loop_K =>
       main_inductive_loop_in_thread_K,
      main_inductive_loop_in_thread_recognize_plates_in_K =>
       main_inductive_loop_in_thread_K,
      main_plates_data_thread_plates_data_in_K =>
       main_plates_data_thread_K,
      main_plates_data_thread_plates_data_in_event_K =>
       main_plates_data_thread_K,
      main_plates_data_thread_open_gate_in_K =>
       main_plates_data_thread_K,
      main_car_passed_entry_thread_car_on_loop_K =>
       main_car_passed_entry_thread_K,
      main_car_passed_entry_thread_close_gate_K =>
       main_car_passed_entry_thread_K,
      main_car_parked_thread_slots_number_K =>
       main_car_parked_thread_K,
      main_car_parked_thread_car_parked_K =>
       main_car_parked_thread_K,
      main_car_moved_thread_slots_number_K =>
       main_car_moved_thread_K,
      main_car_moved_thread_car_moved_K =>
       main_car_moved_thread_K,
      main_inductive_loop_out_thread_car_on_loop_K =>
       main_inductive_loop_out_thread_K,
      main_inductive_loop_out_thread_recognize_plates_out_K =>
       main_inductive_loop_out_thread_K,
      main_calculate_price_plate_number_event_K =>
       main_calculate_price_K,
      main_calculate_price_plate_number_K =>
       main_calculate_price_K,
      main_calculate_price_calculated_price_K =>
       main_calculate_price_K,
      main_open_gate_out_thread_parking_paid_K =>
       main_open_gate_out_thread_K,
      main_open_gate_out_thread_open_gate_out_K =>
       main_open_gate_out_thread_K,
      main_car_passed_exit_thread_car_on_loop_K =>
       main_car_passed_exit_thread_K,
      main_car_passed_exit_thread_close_gate_K =>
       main_car_passed_exit_thread_K);

  Max_Port_Image_Size : constant Standard.Integer :=
   53;

  --  Maximal Port_Image size for this node

  subtype Port_Sized_String is
   Standard.String
     (1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size);

  --  Port Image

  type UT_Deployment_Main_Port_Image_Array is
   array (UT_Deployment_Main_Port_Type_Range)
     of Port_Sized_String;

  Port_Image : constant UT_Deployment_Main_Port_Image_Array :=
   UT_Deployment_Main_Port_Image_Array'
     (main_inductive_loop_in_thread_car_on_loop_K =>
       "main_inductive_loop_in_thread_car_on_loop_K          ",
      main_inductive_loop_in_thread_recognize_plates_in_K =>
       "main_inductive_loop_in_thread_recognize_plates_in_K  ",
      main_plates_data_thread_plates_data_in_K =>
       "main_plates_data_thread_plates_data_in_K             ",
      main_plates_data_thread_plates_data_in_event_K =>
       "main_plates_data_thread_plates_data_in_event_K       ",
      main_plates_data_thread_open_gate_in_K =>
       "main_plates_data_thread_open_gate_in_K               ",
      main_car_passed_entry_thread_car_on_loop_K =>
       "main_car_passed_entry_thread_car_on_loop_K           ",
      main_car_passed_entry_thread_close_gate_K =>
       "main_car_passed_entry_thread_close_gate_K            ",
      main_car_parked_thread_slots_number_K =>
       "main_car_parked_thread_slots_number_K                ",
      main_car_parked_thread_car_parked_K =>
       "main_car_parked_thread_car_parked_K                  ",
      main_car_moved_thread_slots_number_K =>
       "main_car_moved_thread_slots_number_K                 ",
      main_car_moved_thread_car_moved_K =>
       "main_car_moved_thread_car_moved_K                    ",
      main_inductive_loop_out_thread_car_on_loop_K =>
       "main_inductive_loop_out_thread_car_on_loop_K         ",
      main_inductive_loop_out_thread_recognize_plates_out_K =>
       "main_inductive_loop_out_thread_recognize_plates_out_K",
      main_calculate_price_plate_number_event_K =>
       "main_calculate_price_plate_number_event_K            ",
      main_calculate_price_plate_number_K =>
       "main_calculate_price_plate_number_K                  ",
      main_calculate_price_calculated_price_K =>
       "main_calculate_price_calculated_price_K              ",
      main_open_gate_out_thread_parking_paid_K =>
       "main_open_gate_out_thread_parking_paid_K             ",
      main_open_gate_out_thread_open_gate_out_K =>
       "main_open_gate_out_thread_open_gate_out_K            ",
      main_car_passed_exit_thread_car_on_loop_K =>
       "main_car_passed_exit_thread_car_on_loop_K            ",
      main_car_passed_exit_thread_close_gate_K =>
       "main_car_passed_exit_thread_close_gate_K             ");

  --  Maximal message payload size for this node (in bits)

  Max_Payload_Size : constant Standard.Integer :=
   112;

  --  Biggest type: integer

end PolyORB_HI_Generated.Deployment;
